---
tasks:
  - name: Copy global common conf
    ansible.builtin.copy:
      src: files/global_common.conf
      dest: /etc/drbd.d/global_common.conf
      owner: root
      group: root
      mode: '0600'

#- name: Copy r0
#  ansible.builtin.copy:
#    src: files/r0.res
#    dest: /etc/drbd.d/r0.res
#    owner: root
#    group: root
#    mode: '0600'

  - name: configure DRBD device
    template: src=r0.j2 dest=/etc/drbd.d/r0.res
    register: drbd0_config
    
  - name: Make sure device DRBD is down
    ansible.builtin.command: drbdadm down {{ drbd_filemame_resource }}

  - name: Wipefs on disk
    ansible.builtin.command: wipefs -afq {{ drbd_backing_disk1 }}

  - name: Wipefs on disk
    ansible.builtin.command: wipefs -afq {{ drbd_backing_disk2 }}

  - name: Create ressource DRBD
    ansible.builtin.command: drbdadm create {{ drbd_filemame_resource }}

  - name: Initialize ressource DRBD
    ansible.builtin.command: drbdadm up {{ drbd_filemame_resource }}

  - name: Make one node primary
    ansible.builtin.command: drbdadm primary --force r0
    when: ansible_hostname == 'lay6lnx0001.gdc.geodis.org'
 
  - name: check status
    ansible.builtin.command: drbdadm status
